---
title: "README"
author: "hrbrmstr"
date: "August 25, 2014"
output:
  md_document:
    variant: markdown_github
---

An alternative visualization for the Vox Donate/Deaths Bubble Chart highlighted in [this thread](https://twitter.com/andrewsu/status/503390627879350272).

```{r}
library(reshape2)
library(ggplot2)
library(scales)
library(gridExtra)
library(RColorBrewer)

vox <- read.csv("data/vox.csv", stringsAsFactors=FALSE)

vox$color <- brewer.pal(8, "Set3")

# Money raised (left bar chart)

gg <- ggplot(data=vox, aes(x=reorder(Disease, Money.Raised), 
                           y=Money.Raised, fill=color))
gg <- gg + geom_bar(stat="identity")
gg <- gg + theme_bw()
gg <- gg + scale_y_reverse()
gg <- gg + coord_flip()
gg <- gg + geom_text(aes(label=sprintf("($%3.2fm) %s\n%s", Money.Raised,
                                       Disease, Event)), y=-5, hjust=1)
gg <- gg + labs(x="", y="", title="Money Raised (large event)")
gg <- gg + theme(legend.position="none")
gg <- gg + theme(panel.border=element_blank())
gg <- gg + theme(panel.grid=element_blank())
gg <- gg + theme(panel.background=element_blank())
gg <- gg + theme(axis.ticks=element_blank())
gg <- gg + theme(axis.text=element_blank())
gg <- gg + theme(plot.margin = unit(c(0,0,0,0), "cm"))
gg <- gg + theme(panel.margin.x = unit(0, "cm"))
gg.money <- gg

# Deaths (right bar chart)

gg <- ggplot(data=vox, aes(x=reorder(Disease, Deaths..US.), 
                           y=Deaths..US., fill=color))
gg <- gg + geom_bar(stat="identity")
gg <- gg + theme_bw()
gg <- gg + coord_flip()
gg <- gg + geom_text(aes(label=sprintf("%s\n%s deaths", Disease, 
                                       format(Deaths..US., big.mark=",", 
                                              scientific=FALSE, trim=TRUE))), 
                     y=10000, hjust=0)
gg <- gg + labs(x="", y="", title="Annual U.S. Deaths")
gg <- gg + theme(legend.position="none")
gg <- gg + theme(panel.border=element_blank())
gg <- gg + theme(panel.grid=element_blank())
gg <- gg + theme(panel.background=element_blank())
gg <- gg + theme(axis.ticks=element_blank())
gg <- gg + theme(axis.text=element_blank())
gg <- gg + theme(plot.margin = unit(c(0,0,0,0), "cm"))
gg <- gg + theme(panel.margin.x = unit(0, "cm"))
gg.deaths <- gg

# 

gg <- ggplot(data=vox, aes(y=reorder(Money.Rank, Money.Raised), 
                           yend=reorder(Deaths.Rank, Money.Raised), 
                           x=0, xend=1, color=color))
gg <- gg + geom_segment(size=2)
gg <- gg + theme_bw()
gg <- gg + labs(x="", y="", title="")
gg <- gg + theme(legend.position="none")
gg <- gg + theme(panel.border=element_blank())
gg <- gg + theme(panel.grid=element_blank())
gg <- gg + theme(panel.background=element_blank())
gg <- gg + theme(panel.background=element_blank())
gg <- gg + theme(axis.ticks=element_blank())
gg <- gg + theme(axis.text=element_blank())
gg <- gg + theme(plot.margin = unit(c(0,-1,0,-1), "lines"))
gg <- gg + theme(panel.margin.y = unit(2, "lines"))
gg <- gg + theme(panel.margin.x = unit(0, "lines"))
gg.slope <- gg
```

```{r, fig.width=11, fig.height=6, warning=FALSE}
grid.arrange(gg.money, gg.slope, gg.deaths, ncol=3, widths=c(0.4, 0.2, 0.4))
```
